services:

  auth-db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5442:5432"

  user-db:
    image: postgres:16
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5443:5432"

  event-db:
    image: postgres:16
    container_name: event_db
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5444:5432"

  payment-db:
    image: postgres:16
    container_name: payment_db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5445:5432"

  ticket-db:
    image: postgres:16
    container_name: ticket_db
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5447:5432"

  notification-db:
    image: postgres:16
    container_name: notification_db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "5446:5432"