name: Docker Hub

on:
  push:
    branches: ["develop"]

jobs:
  docker:
    name: Build & Push (${{ matrix.service }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api-gateway
          - auth-service
          - event-service
          - ticket-service
          - user-service
          - payment-service
          - notification-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/eventflow-${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: backend/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
